file=open('faizan.txt','r')
print('Is file readable?-->',file.readable())
cont=file.readlines()
print(cont)
file.seek(0,0)
cont=file.readline()
print(cont)
file.seek(0,0)
cont=file.read()
print(cont)
file.close()
